// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: interviews.sql

package db

import (
	"context"
	"database/sql"
)

const deleteInterview = `-- name: DeleteInterview :exec
DELETE FROM interviews
WHERE id = ?
`

func (q *Queries) DeleteInterview(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteInterviewStmt, deleteInterview, id)
	return err
}

const getInterviewByID = `-- name: GetInterviewByID :one
SELECT id, title, message_count, prompt_tokens, completion_tokens, cost, summary_message_id, todos, difficulty, topic, status, updated_at, created_at
FROM interviews
WHERE id = ? LIMIT 1
`

func (q *Queries) GetInterviewByID(ctx context.Context, id string) (Interview, error) {
	row := q.queryRow(ctx, q.getInterviewByIDStmt, getInterviewByID, id)
	var i Interview
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.MessageCount,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.Cost,
		&i.SummaryMessageID,
		&i.Todos,
		&i.Difficulty,
		&i.Topic,
		&i.Status,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listInterviews = `-- name: ListInterviews :many
SELECT id, title, message_count, prompt_tokens, completion_tokens, cost, summary_message_id, todos, difficulty, topic, status, updated_at, created_at
FROM interviews
ORDER BY updated_at DESC
`

func (q *Queries) ListInterviews(ctx context.Context) ([]Interview, error) {
	rows, err := q.query(ctx, q.listInterviewsStmt, listInterviews)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Interview{}
	for rows.Next() {
		var i Interview
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.MessageCount,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.Cost,
			&i.SummaryMessageID,
			&i.Todos,
			&i.Difficulty,
			&i.Topic,
			&i.Status,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInterview = `-- name: UpdateInterview :one
UPDATE interviews
SET
    title = ?,
    message_count = ?,
    prompt_tokens = ?,
    completion_tokens = ?,
    cost = ?,
    summary_message_id = ?,
    todos = ?,
    difficulty = ?,
    topic = ?,
    status = ?
WHERE id = ?
RETURNING id, title, message_count, prompt_tokens, completion_tokens, cost, summary_message_id, todos, difficulty, topic, status, updated_at, created_at
`

type UpdateInterviewParams struct {
	Title            string         `json:"title"`
	MessageCount     int64          `json:"message_count"`
	PromptTokens     int64          `json:"prompt_tokens"`
	CompletionTokens int64          `json:"completion_tokens"`
	Cost             float64        `json:"cost"`
	SummaryMessageID sql.NullString `json:"summary_message_id"`
	Todos            sql.NullString `json:"todos"`
	Difficulty       sql.NullString `json:"difficulty"`
	Topic            sql.NullString `json:"topic"`
	Status           sql.NullString `json:"status"`
	ID               string         `json:"id"`
}

func (q *Queries) UpdateInterview(ctx context.Context, arg UpdateInterviewParams) (Interview, error) {
	row := q.queryRow(ctx, q.updateInterviewStmt, updateInterview,
		arg.Title,
		arg.MessageCount,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.Cost,
		arg.SummaryMessageID,
		arg.Todos,
		arg.Difficulty,
		arg.Topic,
		arg.Status,
		arg.ID,
	)
	var i Interview
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.MessageCount,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.Cost,
		&i.SummaryMessageID,
		&i.Todos,
		&i.Difficulty,
		&i.Topic,
		&i.Status,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateInterviewTitleAndUsage = `-- name: UpdateInterviewTitleAndUsage :exec
UPDATE interviews
SET
    title = ?,
    prompt_tokens = prompt_tokens + ?,
    completion_tokens = completion_tokens + ?,
    cost = cost + ?
WHERE id = ?
`

type UpdateInterviewTitleAndUsageParams struct {
	Title            string  `json:"title"`
	PromptTokens     int64   `json:"prompt_tokens"`
	CompletionTokens int64   `json:"completion_tokens"`
	Cost             float64 `json:"cost"`
	ID               string  `json:"id"`
}

func (q *Queries) UpdateInterviewTitleAndUsage(ctx context.Context, arg UpdateInterviewTitleAndUsageParams) error {
	_, err := q.exec(ctx, q.updateInterviewTitleAndUsageStmt, updateInterviewTitleAndUsage,
		arg.Title,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.Cost,
		arg.ID,
	)
	return err
}
